notifications:
  email: false
language: python
python:
  - "3.5"
install:
  - pip install .
  - pip install falcon
  - pip install -r requirements.txt
script:
  - python -m compileall -f falcon_ask
  - py.test -vvv
